version: "2"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
    ports:
      - "8000:8000"
    links:
      - redis